@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon May 05 10:30:02 +0200 2025
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 5f9cfa43c0d14876a6f7ce80477bea82 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot sim_top_behav xil_defaultlib.sim_top -log elaborate.log"
call xelab  -wto 5f9cfa43c0d14876a6f7ce80477bea82 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot sim_top_behav xil_defaultlib.sim_top -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
